name: Build Android TWA

on:
  push:
    branches: [main, master]
    tags:
      - 'v*'
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'debug'
        type: choice
        options:
          - debug
          - release

jobs:
  validate-pwa:
    name: Validate PWA
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build PWA
        run: npm run build

      - name: Install Bubblewrap CLI
        run: npm install -g @bubblewrap/cli

      - name: Validate PWA
        run: bubblewrap validate --url https://www.vikoba.xyz

  build-android:
    name: Build Android App
    runs-on: ubuntu-latest
    needs: validate-pwa

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Bubblewrap CLI
        run: npm install -g @bubblewrap/cli

      - name: Decode keystore
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        env:
          KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
        run: |
          echo "$KEYSTORE_BASE64" | base64 --decode > android.keystore

      - name: Build Android App Bundle (Release)
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        env:
          BUBBLEWRAP_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
        run: |
          bubblewrap build --skipPwaValidation

      - name: Build Android APK (Debug)
        if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.release_type == 'debug')
        run: |
          bubblewrap build

      - name: Upload APK artifact (Debug)
        if: github.event_name == 'pull_request' || (github.event_name == 'workflow_dispatch' && github.event.inputs.release_type == 'debug')
        uses: actions/upload-artifact@v4
        with:
          name: vikoba-debug-apk
          path: app-release-signed.apk
          retention-days: 30

      - name: Upload AAB artifact (Release)
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
        uses: actions/upload-artifact@v4
        with:
          name: vikoba-release-bundle
          path: app-release-bundle.aab
          retention-days: 90

      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            app-release-bundle.aab
            app-release-signed.apk
          draft: true
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-to-play-store:
    name: Deploy to Play Store
    runs-on: ubuntu-latest
    needs: build-android
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download AAB artifact
        uses: actions/download-artifact@v4
        with:
          name: vikoba-release-bundle

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Fastlane
        run: gem install fastlane

      - name: Deploy to Play Store (Internal Testing)
        env:
          PLAY_STORE_CONFIG_JSON: ${{ secrets.PLAY_STORE_CONFIG_JSON }}
        run: |
          echo "$PLAY_STORE_CONFIG_JSON" > play-store-config.json
          fastlane supply \
            --aab app-release-bundle.aab \
            --track internal \
            --json_key play-store-config.json \
            --package_name xyz.vikoba.app \
            --skip_upload_metadata \
            --skip_upload_images \
            --skip_upload_screenshots
